apiVersion: v1
kind: Service
metadata:
  name: todosvc-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  todosvc
      prefix: /todo/
      service: todosvc-service:5001
      host_rewrite: todosvc-service
spec:
  type: ClusterIP
  selector:
    app: todosvc
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
